name: Deploy to staging (branch master)

on:
  push:
    branches:
      - master

jobs:
  redeploy_allserver:
    name: Deploying every server to staging
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@64.227.147.124 << 'EOF'
            set -e

            export NVM_DIR="/root/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm use 22

            command -v pnpm >/dev/null 2>&1 || npm install -g pnpm
            command -v pm2  >/dev/null 2>&1 || npm install -g pm2

            cd excalidraw-realtime-editor || exit 1
            git pull origin master

            pnpm install
            pnpm run build

            pm2 restart excalidraw-frontend
            pm2 restart http-backend
            pm2 restart ws-backend
          EOF






# name: Deploy to staging (branch master)

# on:
#   push:
#     branches:
#       - master

# jobs:
#   redeploy_allserver:
#     name: Deploying every server to staging
#     runs-on: ubuntu-latest

#     steps:
#       - name: Setup SSH
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
#           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#           chmod 700 ~/.ssh/id_rsa

#       - name: Deploy via SSH
#         run: |
#           ssh root@64.227.147.124 << 'EOF'
#             cd excalidraw-realtime-editor || exit 1
#             git pull
#             pnpm install
#             pnpm run build
#             pm2 restart excalidraw-frontend
#             pm2 restart http-backend
#             pm2 restart ws-backend
#           EOF















          